dataset_limit: 0
# dataset_limit: 5000
embedding_chunk_size: 100
train_params:
  benchmark:
    num_epochs: 10
    batch_size: 64
    model_save_interval_epochs: 1
    proba_threshold: 0.5
    log_interval: 100
    loss_margin: 0.0
    hidden_dim: 384
    output_dim: 384
    lr: 0.001
  setup_1:
    num_epochs: 50
    batch_size: 64
    model_save_interval_epochs: 5
    proba_threshold: 0.5
    log_interval: 500
    loss_margin: 0.0
    hidden_dim: 128
    output_dim: 64
    lr: 0.0005
